Category.create!([
  {group: "special", hierarchy: ["Service", "Utilities", "Water"], plaid_category_id: "18068001", rank: 3, descriptive_name: "Utilities", essential: true},
  {group: "special", hierarchy: ["Service", "Utilities", "Sanitary and Waste Management"], plaid_category_id: "18068002", rank: 3, descriptive_name: "Utilities", essential: true},
  {group: "place", hierarchy: ["Service", "Utilities", "Heating, Ventilating, and Air Conditioning"], plaid_category_id: "18068003", rank: 3, descriptive_name: "Utilities", essential: true},
  {group: "special", hierarchy: ["Service", "Utilities", "Gas"], plaid_category_id: "18068004", rank: 3, descriptive_name: "Utilities", essential: true},
  {group: "special", hierarchy: ["Service", "Utilities", "Electric"], plaid_category_id: "18068005", rank: 3, descriptive_name: "Utilities", essential: true},
  {group: "digital", hierarchy: ["Service", "Internet Services"], plaid_category_id: "18031000", rank: 2, descriptive_name: "Utilities", essential: true},
  {group: "place", hierarchy: ["Community"], plaid_category_id: "12000000", rank: 1, descriptive_name: "Community", essential: true},
  {group: "special", hierarchy: ["Bank Fees", "Overdraft"], plaid_category_id: "10001000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "ATM"], plaid_category_id: "10002000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "Late Payment"], plaid_category_id: "10003000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "Fraud Dispute"], plaid_category_id: "10004000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "Foreign Transaction"], plaid_category_id: "10005000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "Wire Transfer"], plaid_category_id: "10006000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "Insufficient Funds"], plaid_category_id: "10007000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "Cash Advance"], plaid_category_id: "10008000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Bank Fees", "Excess Activity"], plaid_category_id: "10009000", rank: 2, descriptive_name: "Bank Fees", essential: false},
  {group: "special", hierarchy: ["Cash Advance"], plaid_category_id: "11000000", rank: 1, descriptive_name: "Cash Advance", essential: false},
  {group: "place", hierarchy: ["Food and Drink"], plaid_category_id: "13000000", rank: 1, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Bar"], plaid_category_id: "13001000", rank: 2, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Bar", "Wine Bar"], plaid_category_id: "13001001", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Bar", "Sports Bar"], plaid_category_id: "13001002", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Bar", "Hotel Lounge"], plaid_category_id: "13001003", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Breweries"], plaid_category_id: "13002000", rank: 2, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Internet Cafes"], plaid_category_id: "13003000", rank: 2, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Nightlife"], plaid_category_id: "13004000", rank: 2, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Nightlife", "Strip Club"], plaid_category_id: "13004001", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Nightlife", "Night Clubs"], plaid_category_id: "13004002", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Nightlife", "Karaoke"], plaid_category_id: "13004003", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Nightlife", "Jazz and Blues Cafe"], plaid_category_id: "13004004", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Nightlife", "Hookah Lounges"], plaid_category_id: "13004005", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Nightlife", "Adult Entertainment"], plaid_category_id: "13004006", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants"], plaid_category_id: "13005000", rank: 2, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Winery"], plaid_category_id: "13005001", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Delis"], plaid_category_id: "13005040", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Bakery"], plaid_category_id: "13005053", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Recreation", "Landmarks", "Monuments and Memorials"], plaid_category_id: "17023001", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Stadiums and Arenas"], plaid_category_id: "17043000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Holding and Investment Offices"], plaid_category_id: "18020005", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Plumbing"], plaid_category_id: "18024007", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Landscaping and Gardeners"], plaid_category_id: "18024013", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Mining", "Non-Metallic Minerals"], plaid_category_id: "18040003", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "News Reporting"], plaid_category_id: "18041000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Agriculture and Forestry", "Crop Production"], plaid_category_id: "18073001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Healthcare", "Physicians"], plaid_category_id: "14002000", rank: 2, descriptive_name: "Healthcare", essential: true},
  {group: "special", hierarchy: ["Interest"], plaid_category_id: "15000000", rank: 1, descriptive_name: "Interest", essential: true},
  {group: "special", hierarchy: ["Interest", "Interest Earned"], plaid_category_id: "15001000", rank: 2, descriptive_name: "Interest", essential: true},
  {group: "special", hierarchy: ["Interest", "Interest Charged"], plaid_category_id: "15002000", rank: 2, descriptive_name: "Interest", essential: true},
  {group: "special", hierarchy: ["Payment"], plaid_category_id: "16000000", rank: 1, descriptive_name: "Payment", essential: true},
  {group: "special", hierarchy: ["Payment", "Credit Card"], plaid_category_id: "16001000", rank: 2, descriptive_name: "Payment", essential: true},
  {group: "special", hierarchy: ["Payment", "Rent"], plaid_category_id: "16002000", rank: 2, descriptive_name: "Payment", essential: true},
  {group: "special", hierarchy: ["Payment", "Loan"], plaid_category_id: "16003000", rank: 2, descriptive_name: "Payment", essential: true},
  {group: "place", hierarchy: ["Recreation"], plaid_category_id: "17000000", rank: 1, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment"], plaid_category_id: "17001000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Theatrical Productions"], plaid_category_id: "17001001", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Symphony and Opera"], plaid_category_id: "17001002", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Sports Venues"], plaid_category_id: "17001003", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Social Clubs"], plaid_category_id: "17001004", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Psychics and Astrologers"], plaid_category_id: "17001005", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Party Centers"], plaid_category_id: "17001006", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Music and Show Venues"], plaid_category_id: "17001007", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Museums"], plaid_category_id: "17001008", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Movie Theatres"], plaid_category_id: "17001009", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Fairgrounds and Rodeos"], plaid_category_id: "17001010", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Entertainment"], plaid_category_id: "17001011", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Dance Halls and Saloons"], plaid_category_id: "17001012", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Circuses and Carnivals"], plaid_category_id: "17001013", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Casinos and Gaming"], plaid_category_id: "17001014", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Bowling"], plaid_category_id: "17001015", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Billiards and Pool"], plaid_category_id: "17001016", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Art Dealers and Galleries"], plaid_category_id: "17001017", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Service", "Construction"], plaid_category_id: "18013000", rank: 2, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive"], plaid_category_id: "18006000", rank: 2, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Motorcycle, Moped and Scooter Repair"], plaid_category_id: "18006002", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Maintenance and Repair"], plaid_category_id: "18006003", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Car Appraisers"], plaid_category_id: "18006005", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Auto Transmission"], plaid_category_id: "18006006", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Auto Tires"], plaid_category_id: "18006007", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Auto Smog Check"], plaid_category_id: "18006008", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Car Wash and Detail"], plaid_category_id: "18006004", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Automotive", "Towing"], plaid_category_id: "18006001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Computers", "Maintenance and Repair"], plaid_category_id: "18012001", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Direct Mail and Email Marketing Services"], plaid_category_id: "18001008", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Creative Services"], plaid_category_id: "18001009", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Advertising Agencies and Media Buyers"], plaid_category_id: "18001010", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Art Restoration"], plaid_category_id: "18003000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Audiovisual"], plaid_category_id: "18004000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Household"], plaid_category_id: "18025000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Travel", "Airports"], plaid_category_id: "22002000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Service", "Packaging"], plaid_category_id: "18043000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Venmo"], plaid_category_id: "21010001", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Square Cash"], plaid_category_id: "21010002", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Square"], plaid_category_id: "21010003", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "PayPal"], plaid_category_id: "21010004", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Dwolla"], plaid_category_id: "21010005", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Coinbase"], plaid_category_id: "21010006", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Chase QuickPay"], plaid_category_id: "21010007", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Acorns"], plaid_category_id: "21010008", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Digit"], plaid_category_id: "21010009", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Betterment"], plaid_category_id: "21010010", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party", "Plaid"], plaid_category_id: "21010011", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Withdrawal"], plaid_category_id: "21012000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Withdrawal", "Check"], plaid_category_id: "21012001", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Withdrawal", "ATM"], plaid_category_id: "21012002", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Save As You Go"], plaid_category_id: "21013000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "place", hierarchy: ["Travel"], plaid_category_id: "22000000", rank: 1, descriptive_name: "Travel", essential: false},
  {group: "special", hierarchy: ["Travel", "Airlines and Aviation Services"], plaid_category_id: "22001000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Boat"], plaid_category_id: "22003000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Bus Stations"], plaid_category_id: "22004000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Car and Truck Rentals"], plaid_category_id: "22005000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Car Service"], plaid_category_id: "22006000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "special", hierarchy: ["Travel", "Car Service", "Ride Share"], plaid_category_id: "22006001", rank: 3, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Charter Buses"], plaid_category_id: "22007000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "special", hierarchy: ["Travel", "Cruises"], plaid_category_id: "22008000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Gas Stations"], plaid_category_id: "22009000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Heliports"], plaid_category_id: "22010000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Limos and Chauffeurs"], plaid_category_id: "22011000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Lodging"], plaid_category_id: "22012000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Lodging", "Resorts"], plaid_category_id: "22012001", rank: 3, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Lodging", "Lodges and Vacation Rentals"], plaid_category_id: "22012002", rank: 3, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Lodging", "Hotels and Motels"], plaid_category_id: "22012003", rank: 3, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Lodging", "Hostels"], plaid_category_id: "22012004", rank: 3, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Lodging", "Cottages and Cabins"], plaid_category_id: "22012005", rank: 3, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Lodging", "Bed and Breakfasts"], plaid_category_id: "22012006", rank: 3, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Rail"], plaid_category_id: "22015000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "special", hierarchy: ["Travel", "Taxi"], plaid_category_id: "22016000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "place", hierarchy: ["Travel", "Transportation Centers"], plaid_category_id: "22018000", rank: 2, descriptive_name: "Travel", essential: false},
  {group: "special", hierarchy: ["Service", "Utilities"], plaid_category_id: "18068000", rank: 2, descriptive_name: "Utilities", essential: true},
  {group: "place", hierarchy: ["Healthcare"], plaid_category_id: "14000000", rank: 1, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Service", "Telecommunication Services"], plaid_category_id: "18063000", rank: 2, descriptive_name: "Utilities", essential: true},
  {group: "place", hierarchy: ["Service", "Water and Waste Management"], plaid_category_id: "18070000", rank: 2, descriptive_name: "Utilities", essential: true},
  {group: "special", hierarchy: ["Bank Fees"], plaid_category_id: "10000000", rank: 1, descriptive_name: "Bank Fees", essential: true},
  {group: "place", hierarchy: ["Service", "Transportation"], plaid_category_id: "18066000", rank: 2, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Community", "Animal Shelter"], plaid_category_id: "12001000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Assisted Living Services"], plaid_category_id: "12002000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Assisted Living Services", "Facilities and Nursing Homes"], plaid_category_id: "12002001", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Assisted Living Services", "Caretakers"], plaid_category_id: "12002002", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Cemetery"], plaid_category_id: "12003000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Courts"], plaid_category_id: "12004000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Disabled Persons Services"], plaid_category_id: "12006000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Drug and Alcohol Services"], plaid_category_id: "12007000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education"], plaid_category_id: "12008000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Vocational Schools"], plaid_category_id: "12008001", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Tutoring and Educational Services"], plaid_category_id: "12008002", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Primary and Secondary Schools"], plaid_category_id: "12008003", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Fraternities and Sororities"], plaid_category_id: "12008004", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Driving Schools"], plaid_category_id: "12008005", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Dance Schools"], plaid_category_id: "12008006", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Culinary Lessons and Schools"], plaid_category_id: "12008007", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Computer Training"], plaid_category_id: "12008008", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Colleges and Universities"], plaid_category_id: "12008009", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Art School"], plaid_category_id: "12008010", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Education", "Adult Education"], plaid_category_id: "12008011", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Government Departments and Agencies"], plaid_category_id: "12009000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Government Lobbyists"], plaid_category_id: "12010000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Housing Assistance and Shelters"], plaid_category_id: "12011000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Law Enforcement"], plaid_category_id: "12012000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Law Enforcement", "Police Stations"], plaid_category_id: "12012001", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Law Enforcement", "Fire Stations"], plaid_category_id: "12012002", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Law Enforcement", "Correctional Institutions"], plaid_category_id: "12012003", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Libraries"], plaid_category_id: "12013000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Military"], plaid_category_id: "12014000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Organizations and Associations"], plaid_category_id: "12015000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Organizations and Associations", "Youth Organizations"], plaid_category_id: "12015001", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Organizations and Associations", "Environmental"], plaid_category_id: "12015002", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Organizations and Associations", "Charities and Non-Profits"], plaid_category_id: "12015003", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Post Offices"], plaid_category_id: "12016000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Public and Social Services"], plaid_category_id: "12017000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Religious"], plaid_category_id: "12018000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Religious", "Temple"], plaid_category_id: "12018001", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Religious", "Synagogues"], plaid_category_id: "12018002", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Religious", "Mosques"], plaid_category_id: "12018003", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Religious", "Churches"], plaid_category_id: "12018004", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Senior Citizen Services"], plaid_category_id: "12019000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Senior Citizen Services", "Retirement"], plaid_category_id: "12019001", rank: 3, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Community", "Day Care and Preschools"], plaid_category_id: "12005000", rank: 2, descriptive_name: "Community", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services"], plaid_category_id: "14001000", rank: 2, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Psychologists"], plaid_category_id: "14001001", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Shops", "Automotive", "Car Dealers and Leasing"], plaid_category_id: "19005007", rank: 3, descriptive_name: "Payment", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Pregnancy and Sexual Health"], plaid_category_id: "14001002", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Podiatrists"], plaid_category_id: "14001003", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Physical Therapy"], plaid_category_id: "14001004", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Optometrists"], plaid_category_id: "14001005", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Nutritionists"], plaid_category_id: "14001006", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Nurses"], plaid_category_id: "14001007", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Mental Health"], plaid_category_id: "14001008", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Medical Supplies and Labs"], plaid_category_id: "14001009", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Hospitals, Clinics and Medical Centers"], plaid_category_id: "14001010", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Emergency Services"], plaid_category_id: "14001011", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Dentists"], plaid_category_id: "14001012", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Counseling and Therapy"], plaid_category_id: "14001013", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Chiropractors"], plaid_category_id: "14001014", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Blood Banks and Centers"], plaid_category_id: "14001015", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Alternative Medicine"], plaid_category_id: "14001016", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Healthcare Services", "Acupuncture"], plaid_category_id: "14001017", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Urologists"], plaid_category_id: "14002001", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Respiratory"], plaid_category_id: "14002002", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Radiologists"], plaid_category_id: "14002003", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Psychiatrists"], plaid_category_id: "14002004", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Plastic Surgeons"], plaid_category_id: "14002005", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Pediatricians"], plaid_category_id: "14002006", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Pathologists"], plaid_category_id: "14002007", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Orthopedic Surgeons"], plaid_category_id: "14002008", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Ophthalmologists"], plaid_category_id: "14002009", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Oncologists"], plaid_category_id: "14002010", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Obstetricians and Gynecologists"], plaid_category_id: "14002011", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Neurologists"], plaid_category_id: "14002012", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Internal Medicine"], plaid_category_id: "14002013", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "General Surgery"], plaid_category_id: "14002014", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Gastroenterologists"], plaid_category_id: "14002015", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Family Medicine"], plaid_category_id: "14002016", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Ear, Nose and Throat"], plaid_category_id: "14002017", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Dermatologists"], plaid_category_id: "14002018", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Cardiologists"], plaid_category_id: "14002019", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Healthcare", "Physicians", "Anesthesiologists"], plaid_category_id: "14002020", rank: 3, descriptive_name: "Healthcare", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Specialty"], plaid_category_id: "18013001", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Roofers"], plaid_category_id: "18013002", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Painting"], plaid_category_id: "18013003", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Masonry"], plaid_category_id: "18013004", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Infrastructure"], plaid_category_id: "18013005", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Heating, Ventilating and Air Conditioning"], plaid_category_id: "18013006", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Electricians"], plaid_category_id: "18013007", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Contractors"], plaid_category_id: "18013008", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Carpet and Flooring"], plaid_category_id: "18013009", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Construction", "Carpenters"], plaid_category_id: "18013010", rank: 3, descriptive_name: "Service", essential: true},
  {group: "special", hierarchy: ["Tax", "Payment"], plaid_category_id: "20002000", rank: 2, descriptive_name: "Tax", essential: true},
  {group: "special", hierarchy: ["Service", "Real Estate", "Rent"], plaid_category_id: "18050010", rank: 3, descriptive_name: "Payment", essential: true},
  {group: "place", hierarchy: ["Service", "Automotive", "Auto Oil and Lube"], plaid_category_id: "18006009", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Apartments, Condos and Houses"], plaid_category_id: "18050009", rank: 3, descriptive_name: "Service", essential: true},
  {group: "special", hierarchy: ["Tax"], plaid_category_id: "20000000", rank: 1, descriptive_name: "Tax", essential: true},
  {group: "special", hierarchy: ["Tax", "Refund"], plaid_category_id: "20001000", rank: 2, descriptive_name: "Tax", essential: true},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Vegan and Vegetarian"], plaid_category_id: "13005002", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Turkish"], plaid_category_id: "13005003", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Thai"], plaid_category_id: "13005004", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Swiss"], plaid_category_id: "13005005", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Sushi"], plaid_category_id: "13005006", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Steakhouses"], plaid_category_id: "13005007", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Spanish"], plaid_category_id: "13005008", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Seafood"], plaid_category_id: "13005009", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Scandinavian"], plaid_category_id: "13005010", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Portuguese"], plaid_category_id: "13005011", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Pizza"], plaid_category_id: "13005012", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Moroccan"], plaid_category_id: "13005013", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Middle Eastern"], plaid_category_id: "13005014", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Mexican"], plaid_category_id: "13005015", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Mediterranean"], plaid_category_id: "13005016", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Latin American"], plaid_category_id: "13005017", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Korean"], plaid_category_id: "13005018", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Juice Bar"], plaid_category_id: "13005019", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Japanese"], plaid_category_id: "13005020", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Italian"], plaid_category_id: "13005021", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Indonesian"], plaid_category_id: "13005022", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Indian"], plaid_category_id: "13005023", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Ice Cream"], plaid_category_id: "13005024", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Greek"], plaid_category_id: "13005025", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "German"], plaid_category_id: "13005026", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Gastropub"], plaid_category_id: "13005027", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "French"], plaid_category_id: "13005028", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Food Truck"], plaid_category_id: "13005029", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Fish and Chips"], plaid_category_id: "13005030", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Filipino"], plaid_category_id: "13005031", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Fast Food"], plaid_category_id: "13005032", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Falafel"], plaid_category_id: "13005033", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Ethiopian"], plaid_category_id: "13005034", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Eastern European"], plaid_category_id: "13005035", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Donuts"], plaid_category_id: "13005036", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Distillery"], plaid_category_id: "13005037", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Diners"], plaid_category_id: "13005038", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Dessert"], plaid_category_id: "13005039", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Cupcake Shop"], plaid_category_id: "13005041", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Cuban"], plaid_category_id: "13005042", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Coffee Shop"], plaid_category_id: "13005043", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Chinese"], plaid_category_id: "13005044", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Caribbean"], plaid_category_id: "13005045", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Cajun"], plaid_category_id: "13005046", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Cafe"], plaid_category_id: "13005047", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Burrito"], plaid_category_id: "13005048", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Burgers"], plaid_category_id: "13005049", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Breakfast Spot"], plaid_category_id: "13005050", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Brazilian"], plaid_category_id: "13005051", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Barbecue"], plaid_category_id: "13005052", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Bagel Shop"], plaid_category_id: "13005054", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Australian"], plaid_category_id: "13005055", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Asian"], plaid_category_id: "13005056", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "American"], plaid_category_id: "13005057", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "African"], plaid_category_id: "13005058", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Food and Drink", "Restaurants", "Afghan"], plaid_category_id: "13005059", rank: 3, descriptive_name: "Food and Drink", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Arcades and Amusement Parks"], plaid_category_id: "17001018", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Arts and Entertainment", "Aquarium"], plaid_category_id: "17001019", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Athletic Fields"], plaid_category_id: "17002000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Baseball"], plaid_category_id: "17003000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Basketball"], plaid_category_id: "17004000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Batting Cages"], plaid_category_id: "17005000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Boating"], plaid_category_id: "17006000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Campgrounds and RV Parks"], plaid_category_id: "17007000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Canoes and Kayaks"], plaid_category_id: "17008000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Combat Sports"], plaid_category_id: "17009000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Cycling"], plaid_category_id: "17010000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Dance"], plaid_category_id: "17011000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Equestrian"], plaid_category_id: "17012000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Football"], plaid_category_id: "17013000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Go Carts"], plaid_category_id: "17014000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Golf"], plaid_category_id: "17015000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Gun Ranges"], plaid_category_id: "17016000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Gymnastics"], plaid_category_id: "17017000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Gyms and Fitness Centers"], plaid_category_id: "17018000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Hiking"], plaid_category_id: "17019000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Hockey"], plaid_category_id: "17020000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Hot Air Balloons"], plaid_category_id: "17021000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Hunting and Fishing"], plaid_category_id: "17022000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Landmarks"], plaid_category_id: "17023000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Landmarks", "Historic Sites"], plaid_category_id: "17023002", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Landmarks", "Gardens"], plaid_category_id: "17023003", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Landmarks", "Buildings and Structures"], plaid_category_id: "17023004", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Miniature Golf"], plaid_category_id: "17024000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Outdoors"], plaid_category_id: "17025000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Outdoors", "Rivers"], plaid_category_id: "17025001", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Outdoors", "Mountains"], plaid_category_id: "17025002", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Outdoors", "Lakes"], plaid_category_id: "17025003", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Outdoors", "Forests"], plaid_category_id: "17025004", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Outdoors", "Beaches"], plaid_category_id: "17025005", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Paintball"], plaid_category_id: "17026000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Parks"], plaid_category_id: "17027000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Parks", "Playgrounds"], plaid_category_id: "17027001", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Parks", "Picnic Areas"], plaid_category_id: "17027002", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Parks", "Natural Parks"], plaid_category_id: "17027003", rank: 3, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Personal Trainers"], plaid_category_id: "17028000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Race Tracks"], plaid_category_id: "17029000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Racquet Sports"], plaid_category_id: "17030000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Racquetball"], plaid_category_id: "17031000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Rafting"], plaid_category_id: "17032000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Recreation Centers"], plaid_category_id: "17033000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Rock Climbing"], plaid_category_id: "17034000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Running"], plaid_category_id: "17035000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Scuba Diving"], plaid_category_id: "17036000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Skating"], plaid_category_id: "17037000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Skydiving"], plaid_category_id: "17038000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Snow Sports"], plaid_category_id: "17039000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Soccer"], plaid_category_id: "17040000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Sports and Recreation Camps"], plaid_category_id: "17041000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Sports Clubs"], plaid_category_id: "17042000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "special", hierarchy: ["Service", "Cable"], plaid_category_id: "18009000", rank: 2, descriptive_name: "Utilities", essential: false},
  {group: "place", hierarchy: ["Recreation", "Swimming"], plaid_category_id: "17044000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Tennis"], plaid_category_id: "17045000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Water Sports"], plaid_category_id: "17046000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Yoga and Pilates"], plaid_category_id: "17047000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Recreation", "Zoo"], plaid_category_id: "17048000", rank: 2, descriptive_name: "Recreation", essential: false},
  {group: "place", hierarchy: ["Service"], plaid_category_id: "18000000", rank: 1, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing"], plaid_category_id: "18001000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Writing, Copywriting and Technical Writing"], plaid_category_id: "18001001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Search Engine Marketing and Optimization"], plaid_category_id: "18001002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Public Relations"], plaid_category_id: "18001003", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Promotional Items"], plaid_category_id: "18001004", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Print, TV, Radio and Outdoor Advertising"], plaid_category_id: "18001005", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Online Advertising"], plaid_category_id: "18001006", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Advertising and Marketing", "Market Research and Consulting"], plaid_category_id: "18001007", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Automation and Control Systems"], plaid_category_id: "18005000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Business and Strategy Consulting"], plaid_category_id: "18007000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Business Services"], plaid_category_id: "18008000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Business Services", "Printing and Publishing"], plaid_category_id: "18008001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Chemicals and Gasses"], plaid_category_id: "18010000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Cleaning"], plaid_category_id: "18011000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Computers"], plaid_category_id: "18012000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Computers", "Software Development"], plaid_category_id: "18012002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Credit Counseling and Bankruptcy Services"], plaid_category_id: "18014000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Dating and Escort"], plaid_category_id: "18015000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Employment Agencies"], plaid_category_id: "18016000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Engineering"], plaid_category_id: "18017000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Entertainment"], plaid_category_id: "18018000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Entertainment", "Media"], plaid_category_id: "18018001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Events and Event Planning"], plaid_category_id: "18019000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial"], plaid_category_id: "18020000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Taxes"], plaid_category_id: "18020001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Student Aid and Grants"], plaid_category_id: "18020002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Stock Brokers"], plaid_category_id: "18020003", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Loans and Mortgages"], plaid_category_id: "18020004", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Fund Raising"], plaid_category_id: "18020006", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Financial Planning and Investments"], plaid_category_id: "18020007", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Credit Reporting"], plaid_category_id: "18020008", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Collections"], plaid_category_id: "18020009", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Check Cashing"], plaid_category_id: "18020010", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Business Brokers and Franchises"], plaid_category_id: "18020011", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Banking and Finance"], plaid_category_id: "18020012", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "ATMs"], plaid_category_id: "18020013", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Financial", "Accounting and Bookkeeping"], plaid_category_id: "18020014", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Food and Beverage"], plaid_category_id: "18021000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Food and Beverage", "Distribution"], plaid_category_id: "18021001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Food and Beverage", "Catering"], plaid_category_id: "18021002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Funeral Services"], plaid_category_id: "18022000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Geological"], plaid_category_id: "18023000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement"], plaid_category_id: "18024000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Upholstery"], plaid_category_id: "18024001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Tree Service"], plaid_category_id: "18024002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Swimming Pool Maintenance and Services"], plaid_category_id: "18024003", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Storage"], plaid_category_id: "18024004", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Roofers"], plaid_category_id: "18024005", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Pools and Spas"], plaid_category_id: "18024006", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Pest Control"], plaid_category_id: "18024008", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Painting"], plaid_category_id: "18024009", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Movers"], plaid_category_id: "18024010", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Mobile Homes"], plaid_category_id: "18024011", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Lighting Fixtures"], plaid_category_id: "18024012", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Kitchens"], plaid_category_id: "18024014", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Interior Design"], plaid_category_id: "18024015", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Housewares"], plaid_category_id: "18024016", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Home Inspection Services"], plaid_category_id: "18024017", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Home Appliances"], plaid_category_id: "18024018", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Heating, Ventilation and Air Conditioning"], plaid_category_id: "18024019", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Hardware and Services"], plaid_category_id: "18024020", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Fences, Fireplaces and Garage Doors"], plaid_category_id: "18024021", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Electricians"], plaid_category_id: "18024022", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Doors and Windows"], plaid_category_id: "18024023", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Contractors"], plaid_category_id: "18024024", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Carpet and Flooring"], plaid_category_id: "18024025", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Carpenters"], plaid_category_id: "18024026", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Home Improvement", "Architects"], plaid_category_id: "18024027", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Human Resources"], plaid_category_id: "18026000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Immigration"], plaid_category_id: "18027000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Import and Export"], plaid_category_id: "18028000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Industrial Machinery and Vehicles"], plaid_category_id: "18029000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "special", hierarchy: ["Service", "Insurance"], plaid_category_id: "18030000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Leather"], plaid_category_id: "18032000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Legal"], plaid_category_id: "18033000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Logging and Sawmills"], plaid_category_id: "18034000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Machine Shops"], plaid_category_id: "18035000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Management"], plaid_category_id: "18036000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing"], plaid_category_id: "18037000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Apparel and Fabric Products"], plaid_category_id: "18037001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Chemicals and Gasses"], plaid_category_id: "18037002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Computers and Office Machines"], plaid_category_id: "18037003", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Electrical Equipment and Components"], plaid_category_id: "18037004", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Food and Beverage"], plaid_category_id: "18037005", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Furniture and Fixtures"], plaid_category_id: "18037006", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Glass Products"], plaid_category_id: "18037007", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Industrial Machinery and Equipment"], plaid_category_id: "18037008", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Leather Goods"], plaid_category_id: "18037009", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Metal Products"], plaid_category_id: "18037010", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Nonmetallic Mineral Products"], plaid_category_id: "18037011", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Paper Products"], plaid_category_id: "18037012", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Petroleum"], plaid_category_id: "18037013", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Plastic Products"], plaid_category_id: "18037014", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Rubber Products"], plaid_category_id: "18037015", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Service Instruments"], plaid_category_id: "18037016", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Textiles"], plaid_category_id: "18037017", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Tobacco"], plaid_category_id: "18037018", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Transportation Equipment"], plaid_category_id: "18037019", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Manufacturing", "Wood Products"], plaid_category_id: "18037020", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Media Production"], plaid_category_id: "18038000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Metals"], plaid_category_id: "18039000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Mining"], plaid_category_id: "18040000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Mining", "Coal"], plaid_category_id: "18040001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Mining", "Metal"], plaid_category_id: "18040002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Oil and Gas"], plaid_category_id: "18042000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Rail"], plaid_category_id: "18049000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Refrigeration and Ice"], plaid_category_id: "18051000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Renewable Energy"], plaid_category_id: "18052000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Research"], plaid_category_id: "18054000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Rubber"], plaid_category_id: "18055000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Scientific"], plaid_category_id: "18056000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Security and Safety"], plaid_category_id: "18057000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Shipping and Freight"], plaid_category_id: "18058000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Software Development"], plaid_category_id: "18059000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Storage"], plaid_category_id: "18060000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Subscription"], plaid_category_id: "18061000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Tailors"], plaid_category_id: "18062000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Textiles"], plaid_category_id: "18064000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Tourist Information and Services"], plaid_category_id: "18065000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Travel Agents and Tour Operators"], plaid_category_id: "18067000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Web Design and Development"], plaid_category_id: "18071000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Welding"], plaid_category_id: "18072000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Agriculture and Forestry"], plaid_category_id: "18073000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Agriculture and Forestry", "Forestry"], plaid_category_id: "18073002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Agriculture and Forestry", "Livestock and Animals"], plaid_category_id: "18073003", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Agriculture and Forestry", "Services"], plaid_category_id: "18073004", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Art and Graphic Design"], plaid_category_id: "18074000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Shops"], plaid_category_id: "19000000", rank: 1, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Adult"], plaid_category_id: "19001000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Antiques"], plaid_category_id: "19002000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Arts and Crafts"], plaid_category_id: "19003000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Auctions"], plaid_category_id: "19004000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Automotive"], plaid_category_id: "19005000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Automotive", "Used Car Dealers"], plaid_category_id: "19005001", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Automotive", "Salvage Yards"], plaid_category_id: "19005002", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Automotive", "RVs and Motor Homes"], plaid_category_id: "19005003", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Automotive", "Motorcycles, Mopeds and Scooters"], plaid_category_id: "19005004", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Automotive", "Classic and Antique Car"], plaid_category_id: "19005005", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Automotive", "Car Parts and Accessories"], plaid_category_id: "19005006", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Beauty Products"], plaid_category_id: "19006000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Bicycles"], plaid_category_id: "19007000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Boat Dealers"], plaid_category_id: "19008000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Bookstores"], plaid_category_id: "19009000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories"], plaid_category_id: "19012000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Women's Store"], plaid_category_id: "19012001", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Swimwear"], plaid_category_id: "19012002", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Shoe Store"], plaid_category_id: "19012003", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Men's Store"], plaid_category_id: "19012004", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Lingerie Store"], plaid_category_id: "19012005", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Kids' Store"], plaid_category_id: "19012006", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Boutique"], plaid_category_id: "19012007", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Clothing and Accessories", "Accessories Store"], plaid_category_id: "19012008", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Computers and Electronics"], plaid_category_id: "19013000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Computers and Electronics", "Video Games"], plaid_category_id: "19013001", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Computers and Electronics", "Mobile Phones"], plaid_category_id: "19013002", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Computers and Electronics", "Cameras"], plaid_category_id: "19013003", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Construction Supplies"], plaid_category_id: "19014000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Convenience Stores"], plaid_category_id: "19015000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Costumes"], plaid_category_id: "19016000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Dance and Music"], plaid_category_id: "19017000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Department Stores"], plaid_category_id: "19018000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "digital", hierarchy: ["Shops", "Digital Purchase"], plaid_category_id: "19019000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Discount Stores"], plaid_category_id: "19020000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Tattooing"], plaid_category_id: "18045001", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Tanning Salons"], plaid_category_id: "18045002", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Spas"], plaid_category_id: "18045003", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Skin Care"], plaid_category_id: "18045004", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Piercing"], plaid_category_id: "18045005", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Massage Clinics and Therapists"], plaid_category_id: "18045006", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Shops", "Electrical Equipment"], plaid_category_id: "19021000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Equipment Rental"], plaid_category_id: "19022000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Service", "Paper"], plaid_category_id: "18044000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care"], plaid_category_id: "18045000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Shops", "Flea Markets"], plaid_category_id: "19023000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Florists"], plaid_category_id: "19024000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Food and Beverage Store"], plaid_category_id: "19025000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Food and Beverage Store", "Specialty"], plaid_category_id: "19025001", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Food and Beverage Store", "Health Food"], plaid_category_id: "19025002", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Food and Beverage Store", "Farmers Markets"], plaid_category_id: "19025003", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Food and Beverage Store", "Beer, Wine and Spirits"], plaid_category_id: "19025004", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Fuel Dealer"], plaid_category_id: "19026000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Furniture and Home Decor"], plaid_category_id: "19027000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Gift and Novelty"], plaid_category_id: "19028000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Glasses and Optometrist"], plaid_category_id: "19029000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Hardware Store"], plaid_category_id: "19030000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Hobby and Collectibles"], plaid_category_id: "19031000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Industrial Supplies"], plaid_category_id: "19032000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Jewelry and Watches"], plaid_category_id: "19033000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Luggage"], plaid_category_id: "19034000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Marine Supplies"], plaid_category_id: "19035000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Music, Video and DVD"], plaid_category_id: "19036000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Musical Instruments"], plaid_category_id: "19037000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Newsstands"], plaid_category_id: "19038000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Office Supplies"], plaid_category_id: "19039000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet"], plaid_category_id: "19040000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Women's Store"], plaid_category_id: "19040001", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Swimwear"], plaid_category_id: "19040002", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Shoe Store"], plaid_category_id: "19040003", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Men's Store"], plaid_category_id: "19040004", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Lingerie Store"], plaid_category_id: "19040005", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Kids' Store"], plaid_category_id: "19040006", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Boutique"], plaid_category_id: "19040007", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Outlet", "Accessories Store"], plaid_category_id: "19040008", rank: 3, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Pawn Shops"], plaid_category_id: "19041000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Pets"], plaid_category_id: "19042000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Pharmacies"], plaid_category_id: "19043000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Photos and Frames"], plaid_category_id: "19044000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Shopping Centers and Malls"], plaid_category_id: "19045000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Sporting Goods"], plaid_category_id: "19046000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Supermarkets and Groceries"], plaid_category_id: "19047000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Tobacco"], plaid_category_id: "19048000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Toys"], plaid_category_id: "19049000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Vintage and Thrift"], plaid_category_id: "19050000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Warehouses and Wholesale Stores"], plaid_category_id: "19051000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Wedding and Bridal"], plaid_category_id: "19052000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Wholesale"], plaid_category_id: "19053000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Lawn and Garden"], plaid_category_id: "19054000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "special", hierarchy: ["Transfer"], plaid_category_id: "21000000", rank: 1, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Third Party"], plaid_category_id: "21010000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "place", hierarchy: ["Service", "Real Estate"], plaid_category_id: "18050000", rank: 2, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Real Estate Development and Title Companies"], plaid_category_id: "18050001", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Real Estate Appraiser"], plaid_category_id: "18050002", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Real Estate Agents"], plaid_category_id: "18050003", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Property Management"], plaid_category_id: "18050004", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Corporate Housing"], plaid_category_id: "18050005", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Commercial Real Estate"], plaid_category_id: "18050006", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Building and Land Surveyors"], plaid_category_id: "18050007", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Real Estate", "Boarding Houses"], plaid_category_id: "18050008", rank: 3, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Repair Services"], plaid_category_id: "18053000", rank: 2, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Veterinarians"], plaid_category_id: "18069000", rank: 2, descriptive_name: "Service", essential: true},
  {group: "place", hierarchy: ["Service", "Personal Care", "Manicures and Pedicures"], plaid_category_id: "18045007", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Laundry and Garment Services"], plaid_category_id: "18045008", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Hair Salons and Barbers"], plaid_category_id: "18045009", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Personal Care", "Hair Removal"], plaid_category_id: "18045010", rank: 3, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Petroleum"], plaid_category_id: "18046000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Photography"], plaid_category_id: "18047000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Service", "Plastics"], plaid_category_id: "18048000", rank: 2, descriptive_name: "Service", essential: false},
  {group: "place", hierarchy: ["Shops", "Cards and Stationery"], plaid_category_id: "19010000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Shops", "Children"], plaid_category_id: "19011000", rank: 2, descriptive_name: "Shops", essential: false},
  {group: "place", hierarchy: ["Travel", "Public Transportation Services"], plaid_category_id: "22014000", rank: 2, descriptive_name: "Travel", essential: true},
  {group: "place", hierarchy: ["Travel", "Parking"], plaid_category_id: "22013000", rank: 2, descriptive_name: "Travel", essential: true},
  {group: "special", hierarchy: ["Travel", "Tolls and Fees"], plaid_category_id: "22017000", rank: 2, descriptive_name: "Travel", essential: true},
  {group: "special", hierarchy: ["Transfer", "Internal Account Transfer"], plaid_category_id: "21001000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "ACH"], plaid_category_id: "21002000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Billpay"], plaid_category_id: "21003000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Check"], plaid_category_id: "21004000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Credit"], plaid_category_id: "21005000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Deposit"], plaid_category_id: "21007000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Deposit", "Check"], plaid_category_id: "21007001", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Deposit", "ATM"], plaid_category_id: "21007002", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Keep the Change Savings Program"], plaid_category_id: "21008000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Payroll"], plaid_category_id: "21009000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Payroll", "Benefits"], plaid_category_id: "21009001", rank: 3, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Wire"], plaid_category_id: "21011000", rank: 2, descriptive_name: "Transfer", essential: false},
  {group: "special", hierarchy: ["Transfer", "Debit"], plaid_category_id: "21006000", rank: 2, descriptive_name: "Transfer", essential: true}
])
